cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path("cart-add/", views.CardAddView.as_view(), name="cart_add"),
    path("cart-change/", views.CartChangeView.as_view(), name="cart_change"),
    path("cart-remove/", views.CartRemoveView.as_view(), name="cart_remove"),
    path("carts-remove/", views.UserCartsRemoveView.as_view(), name="carts_remove"),
]

catalog/urls.py
from django.urls import path

from catalog import views

app_name = "catalog"

urlpatterns = [
    path("", views.CatalogView.as_view(), name="catalog"),
    path("", views.CatalogView.as_view(), name="search"),
    path("<slug:item_slug>", views.ItemView.as_view(), name="item"),
]

hanbild/urls.py
from django.conf.urls import handler500
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from hanbild import settings
from hanbild.settings import DEBUG

handler404 = "main.views.page404exception"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("product/", include("product.urls", namespace="product")),
    path("services/", include("solution.urls", namespace="solution")),
    path("order/", include("order.urls", namespace="order")),
    path("vacancies/", include("vacancy.urls", namespace="vacancy")),
    prefix_default_language=False,
)

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from order import views

app_name = "order"

urlpatterns = [
    path("", views.OrderView.as_view(), name="order"),
    path("success-order/", views.SuccessOrderView.as_view(), name="success-order"),
]

cart/models.py
from django.db import models
from catalog.models import Goods


class CartQueryset(models.QuerySet):
    def total_price(self):
        if self:
            return sum(cart.goods_price() for cart in self)
        return 0

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):
    item = models.ForeignKey(to=Goods, on_delete=models.CASCADE, verbose_name="Товар")
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name="Кількість")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата додадання"
    )
    session_key = models.CharField(max_length=32, null=True, blank=True)

    class Meta:
        db_table = "cart"
        verbose_name = "корзину"
        verbose_name_plural = "Корзина"

    objects = CartQueryset().as_manager()

    def __str__(self) -> str:
        return f"Товар: {self.item.name} | Кількість: {self.quantity}"

    def goods_price(self):
        return self.item.price * self.quantity

cart/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View

from cart.models import Cart
from cart.utils import get_user_carts
from catalog.models import Goods
from main.views import BaseApplicationFormView
from django.utils.translation import gettext_lazy as _


class CardAddView(View):
    """Card view to add item in cart which interact with ajax"""

    def post(self, request):
        """Function for adding item to cart"""
        item = Goods.objects.get(id=request.POST.get("product_id"))
        carts = Cart.objects.filter(session_key=request.session.session_key, item=item)
        if carts.exists():
            if cart := carts.first():
                cart.quantity += 1
                cart.save()
        else:
            # Create apart record in db
            Cart.objects.create(
                session_key=request.session.session_key, item=item, quantity=1
            )

        return JsonResponse(
            {
                "message": _("Товар доданий в корзину"),
            }
        )


class CartChangeView(View):
    """Card view to change item in cart which interact with ajax"""

    def post(self, request):
        cart = Cart.objects.get(id=request.POST.get("cart_id"))
        cart.quantity = request.POST.get("quantity")
        cart.save()
        user_carts = get_user_carts(request)
        # if do some action - change part of html template
        string_html = render_to_string(
            "cart/includes/_included_cart.html", {"carts": user_carts}, request=request
        )
        return JsonResponse(
            {
                "cart_items_html": string_html,
                "total_quantity": user_carts.total_quantity(),
            }
        )


class CartRemoveView(View):
    """Card view to remove item from cart which interact with ajax"""

    def post(self, request):
        try:
            Cart.objects.get(id=request.POST.get("cart_id")).delete()
        except Cart.DoesNotExist:
            print("Помилка: об'єкт не знайдено!")
        user_carts = get_user_carts(request)
        string_html = render_to_string(
            "cart/includes/_included_cart.html",
            {"carts": user_carts},
            request=request,
        )
        return JsonResponse(
            {
                "message": _("Товар видалено з корзини"),
                "cart_items_html": string_html,
                "total_quantity": user_carts.total_quantity(),
            }
        )


class UserCartsRemoveView(View):
    """Card view to remove all user carts"""

    def post(self, request):
        session_key = request.session.session_key
        try:
            carts = Cart.objects.filter(session_key=session_key)
            carts.delete()
        except Cart.DoesNotExist:
            print("Помилка: об'єкти не знайдено!")
        except Exception as e:
            print(f"Помилка: {e}")
        return JsonResponse({})


class CartView(BaseApplicationFormView):
    """Cart page view"""

    template_name = "cart/cart.html"
    success_url = reverse_lazy("cart:cart")
    title = _("Корзина")

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load carts_tags %}

{% block title %}
  {% translate 'Корзина' %}
{% endblock %}

{% block meta %}
<meta name="robots" content="noindex, nofollow">
{% endblock %}

{% block content %}
  <main id="cartTabId" class="main">
    {% anonymous_user_carts request as carts %}
    {% if carts %}
      <div class="shopping_cart">
        <div class="cart-heading">
          <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 418.919 418.919" style="enable-background:new 0 0 512 512" xml:space="preserve" class="">
            <g>
              <path d="M0 90.019h285.87v160.79H0z" fill="#000000" opacity="1" data-original="#000000" class=""></path>
              <path d="m418.919 205.005-29.388-65.723H298.69v123.641H34.511v28.108h29.391c-.235 1.598-.397 3.219-.397 4.881 0 18.219 14.65 32.988 32.723 32.988s32.723-14.77 32.723-32.988c0-1.662-.162-3.283-.397-4.881H161.6c-.235 1.598-.397 3.219-.397 4.881 0 18.219 14.65 32.988 32.723 32.988 18.071 0 32.722-14.77 32.722-32.988 0-1.662-.161-3.283-.396-4.881h78.869c-.235 1.598-.397 3.219-.397 4.881 0 18.219 14.65 32.988 32.723 32.988 18.071 0 32.722-14.77 32.722-32.988 0-1.662-.161-3.283-.396-4.881h49.146v-86.026zM96.227 308.824c-7.074 0-12.809-5.781-12.809-12.912 0-1.729.343-3.374.953-4.881 1.91-4.711 6.495-8.033 11.855-8.033s9.945 3.322 11.855 8.033c.61 1.507.953 3.152.953 4.881.001 7.131-5.733 12.912-12.807 12.912zm97.696 0c-7.074 0-12.809-5.781-12.809-12.912 0-1.729.343-3.374.953-4.881 1.91-4.711 6.495-8.033 11.855-8.033s9.945 3.322 11.854 8.033c.611 1.507.954 3.152.954 4.881.001 7.131-5.733 12.912-12.807 12.912zm143.519 0c-7.074 0-12.809-5.781-12.809-12.912 0-1.729.343-3.374.953-4.881 1.91-4.711 6.495-8.033 11.855-8.033s9.945 3.322 11.854 8.033c.611 1.507.954 3.152.954 4.881.002 7.131-5.732 12.912-12.807 12.912zm-17.123-105.056a.889.889 0 0 1-.889-.889v-44.402c0-.491.397-.889.889-.889h55.921c1.179 0 2.246.698 2.718 1.779l19.4 44.401h-78.039z" fill="#000000" opacity="1" data-original="#000000" class=""></path>
            </g>
          </svg>
          <h2>{% translate 'Кошик' %}</h2>
        </div>
        <div class="cart-table" id="cartContainer">
          {% include 'cart/includes/_included_cart.html' %}
        </div>
        <div class="form-buttons">
          <a href="{% url 'catalog:catalog' %}">{% translate 'До каталогу' %}</a>
          <a href="{% url 'order:order' %}">{% translate 'Оформити замовлення' %}</a>
          <a class="remove-all-carts" data-url="{% url 'cart:carts_remove' %}">
            {% csrf_token %}
            <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 32 32" style="enable-background:new 0 0 512 512" xml:space="preserve" class="">
              <g>
                <path d="M28 4h-7V2a1 1 0 0 0-1-1h-8a1 1 0 0 0-1 1v2H4a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h1v18c0 2.206 1.794 4 4 4h14c2.206 0 4-1.794 4-4V9h1a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1zM13 3h6v1h-6zm12 24c0 1.103-.897 2-2 2H9c-1.103 0-2-.897-2-2V9h18zm2-20H5V6h22zM15 26V12a1 1 0 0 1 2 0v14a1 1 0 0 1-2 0zm-5 0V12a1 1 0 0 1 2 0v14a1 1 0 0 1-2 0zm10 0V12a1 1 0 1 1 2 0v14a1 1 0 1 1-2 0z" opacity="1" data-original="#000000" class=""></path>
              </g>
            </svg>
          </a>
        </div>
      </div>
    {% else %}
      {% include 'cart/includes/_included_empty_cart.html' %}
    {% endif %}
  </main>
{% endblock %}