cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path("cart-add/", views.CardAddView.as_view(), name="cart_add"),
    path("cart-change/", views.CartChangeView.as_view(), name="cart_change"),
    path("cart-remove/", views.CartRemoveView.as_view(), name="cart_remove"),
    path("carts-remove/", views.UserCartsRemoveView.as_view(), name="carts_remove"),
]

hanbild/urls.py
from django.conf.urls import handler500
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from hanbild import settings
from hanbild.settings import DEBUG

handler404 = "main.views.page404exception"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("product/", include("product.urls", namespace="product")),
    path("services/", include("solution.urls", namespace="solution")),
    path("order/", include("order.urls", namespace="order")),
    path("vacancies/", include("vacancy.urls", namespace="vacancy")),
    prefix_default_language=False,
)

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from main import views

app_name = "main"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("contacts/", views.ContactsView.as_view(), name="contacts"),
    path("delivery/", views.DeliveryView.as_view(), name="delivery"),
    path("privacy-policy/", views.PrivacyPolicyView.as_view(), name="privacy_policy"),
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name="config/robots.txt", content_type="text/plain")),
    re_path(r'^sitemap\.xml$', TemplateView.as_view(template_name="config/sitemap.xml", content_type="application/xml")),
]

solution/urls.py
from django.urls import path

from solution import views

app_name = "solution"

urlpatterns = [
    path("", views.SolutionView.as_view(), name="solution"),
    path("<slug:slug>", views.SolutionPageView.as_view(), name="solution_page"),
]

main/models.py
from django.db import models


class ClientMessages(models.Model):
    name = models.CharField(max_length=150, verbose_name="Ім'я", null=True, blank=True, default="Ім'я не вказано")
    number_or_email = models.CharField(max_length=200, verbose_name="Номер або email")
    message = models.TextField(verbose_name="Повідомлення", null=True, blank=True, default="Повідомлення не вказано")
    send_message_time = models.DateTimeField(auto_now_add=True, verbose_name="Дата повідомлення")

    def __str__(self):
        return f"{self.name} - {self.number_or_email}"

    class Meta:
        db_table = "client_message"
        verbose_name = "повідомлення клієнта"
        verbose_name_plural = "Повідомлення клієнтів"

solution/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field
from embed_video.fields import EmbedVideoField

from hanbild.utils import set_translation_attrs


class Solution(models.Model):

    solution_title = models.CharField(
        max_length=250,
        verbose_name="Назва сервісу",
    )

    slug = models.SlugField(
        max_length=200,
        unique=True,
        null=True,
        verbose_name="URL",
    )

    index_on_page = models.IntegerField(
        verbose_name="Порядковий номер",
        validators=[MinValueValidator(0)],
        default=0,
    )

    review_content = models.TextField(verbose_name="Вступний текст")

    review_image = models.ImageField(
        upload_to="solution_images",
        verbose_name="Фото до вступного тексту",
    )

    content = CKEditor5Field(
        "Контент",
        null=True,
        blank=True,
        config_name="extends",
    )
    title = models.CharField(
        max_length=250,
        verbose_name="Назва сторінки",
        blank=True,
        null=True,
    )
    description = models.TextField(
        verbose_name="Опис для метатегу",
        blank=True,
        null=True,
    )

    class Meta:
        db_table = "solution"
        verbose_name = "послуга"
        verbose_name_plural = "Послуги"

    def save(self, *args, **kwargs):
        set_translation_attrs(self, ("solution_title", "review_content"))
        return super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.solution_title}"


class SolutionPhotos(models.Model):
    solution = models.ForeignKey(
        to=Solution,
        on_delete=models.CASCADE,
        null=True,
        verbose_name="Послуга",
    )
    image = models.ImageField(
        upload_to="solution_images",
        verbose_name="Фото",
    )

    def __str__(self):
        return f"Фото для послуги: {self.solution}"

    class Meta:
        db_table = "solution_photo"
        verbose_name = "фото послуги"
        verbose_name_plural = "Фото послуги"


class SolutionVideos(models.Model):
    solution = models.ForeignKey(
        to=Solution,
        on_delete=models.CASCADE,
        null=True,
        verbose_name="Послуга",
    )
    video = EmbedVideoField(verbose_name="Посилання на відео")

    def __str__(self):
        return f"Відео для категорії: {self.solution}"

    class Meta:
        db_table = "solution_videos"
        verbose_name = "відео послуги"
        verbose_name_plural = "Відео послуги"

solution/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from main.views import BaseApplicationFormView
from solution.models import Solution, SolutionPhotos, SolutionVideos


class SolutionView(BaseApplicationFormView):
    template_name = "solution/solutions.html"
    success_url = reverse_lazy("solution:solution")
    title = _(
        "Послуги HanBild: виробництво та обслуговування причепів та напівпричепів"
    )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["solutions"] = Solution.objects.filter()
        return context


class SolutionPageView(BaseApplicationFormView):
    template_name = "solution/solution_page.html"
    success_url = reverse_lazy("solution:solution_page")

    def get(self, request, slug, *args, **kwargs):
        solution = get_object_or_404(Solution, slug=slug)
        solution_photos = SolutionPhotos.objects.filter(solution=solution)
        solution_videos = SolutionVideos.objects.filter(solution=solution)

        return render(
            request,
            self.template_name,
            {
                "solution": solution,
                "solution_photos": solution_photos,
                "solution_videos": solution_videos,
            },
        )

    def dispatch(self, request, *args, **kwargs):
        self.success_url = reverse_lazy(
            "solution:solution_page",
            kwargs={
                "slug": kwargs["slug"],
            },
        )
        return super().dispatch(request, *args, **kwargs)

solution/templates/solution/solution_page.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load embed_video_tags %}

{% block title %}
  {{ solution.title }}
{% endblock %}

{% block meta %}
  <meta name="description" content="{{ solution.description }}" />
  <meta property="og:title" content="{{ solution.title }}" />
  <meta property="og:description" content="{{ solution.description }}" />
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
{% endblock %}

{% block content %}
  <main class="main">
    <div class="up-main-section">
      {% url 'solution:solution' as previus_url %}
      {% translate 'Послуги' as previus_title %}
      {% include 'includes/_breadcrumbs.html' with current_url=solution.slug current_title=solution.solution_title|truncatechars:10 previus_url=previus_url previus_title=previus_title %}
    </div>
    <div class="product-page solution-page">
      <div class="photo-block">
        <div class="left-container">
          <div class="info">
            <h1>{{ solution.solution_title }}</h1>
          </div>
        </div>
        <div class="right-container"></div>
      </div>
      <div class="service-blog-container">{{ solution.content|safe }}</div>
      {% include 'includes/_slider.html' with item_photos=solution_photos item_videos=solution_videos alt=solution.solution_title review_image=solution.review_image %}
      <div class="contacts-info background-off">
        <form class="feedback-form" method="post" id="page-contact-form">
          {% csrf_token %}
          <h3>{% translate "Форма зворотнього зв'язку" %}</h3>
          <div class="form-container">
            <div class="point">
              <label for="id_name">{% translate 'Як до вас звертатися:' %}</label>
              <input type="text" name="name" id="id_name" required placeholder="{% translate 'Ваше ім`я' %}" />
              <div id="page_name" class="page-validation-error"></div>
            </div>
            <div class="point">
              <label for="id_number_or_email">{% translate 'Номер телефону або e-mail:' %}</label>
              <input type="text" name="number_or_email" id="id_number_or_email" required placeholder="{% translate 'Залиште контакт для зв`язку' %}" />
              <div id="page_number_or_email" class="page-validation-error"></div>
            </div>
            <div class="point">
              <label for="id_message">{% translate 'Повідомлення:' %}</label>
              <textarea name="message" id="id_message" placeholder="{% translate 'Напишіть, що саме вас цікавить' %}"></textarea>
            </div>
          </div>
          <div class="form-end">
            <input type="checkbox" id="contact-agreement" value="" checked /><label for="contact-agreement">{% translate 'Натискаючи кнопку "Надіслати" я погоджуюсь з умовами' %} <a href="{% url 'main:privacy_policy' %}"><span>{% translate 'політики конфіденційності' %}</span></a></label>

            <div class="form-buttons">
              <a class="contact-submit-button-wrapper"><button class="contact-submit-button" type="submit">{% translate 'Надіслати' %}</button></a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </main>
{% endblock %}

{% block js %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  <script src="{% static 'hanbild/js/swiper.js' %}"></script>
{% endblock %}

solution/templates/solution/solutions.html
{% extends 'base.html' %}
{% load i18n %}

{% block meta %}
  <meta name="description" content="{% translate 'Професійні послуги з виготовлення та обслуговування причепів, напівпричепів та вантажної техніки від HanBild. Висока якість продукції ✓. Індивідуальний підхід ✓. Доставка по всій Україні ✈.' %}" />
  <meta property="og:title" content="{{ title }}" />
  <meta property="og:description" content="{% translate 'Професійні послуги з виготовлення та обслуговування причепів, напівпричепів та вантажної техніки від HanBild. Висока якість продукції ✓. Індивідуальний підхід ✓. Доставка по всій Україні ✈.' %}" />
{% endblock %}

{% block title %}
  {{ title }}
{% endblock %}

{% block css %}
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
{% endblock %}

{% block content %}
  <main class="main" id="margin-bt">
    <div class="up-main-section">
      {% url 'solution:solution' as current_url %}
      {% translate 'Послуги' as current_title %}
      {% include 'includes/_breadcrumbs.html' with current_url=current_url current_title=current_title %}
    </div>
    <div class="services-page">
      <div class="photo-block">
        <div class="left-container">
          <div class="info">
            <h1>{% translate 'Послуги HanBild' %}</h1>
            <p>
              {% translate 'Наша компанія надає широкий спектр послуг. На цій сторінці ви знайдете детальну інформацію про кожну з них. Наша команда гарантує якісне виконання усіх завдань, враховуючи індивідуальні потреби та вимоги кожного клієнта.' %}
            </p>
          </div>
          <div></div>
        </div>
      </div>
      <div class="product-cards services-cards">
        {% for solution in solutions %}
          <div id="{{ solution.index_on_page }}" style="margin-top: -155px; padding-top: 155px;"></div>
          {% if forloop.counter0|divisibleby:2 %}
            {% include 'solution/includes/_left_card.html' with solution=solution %}
          {% else %}
            {% include 'solution/includes/_right_card.html' with solution=solution %}
          {% endif %}
          <div id="{{ solution.index_on_page }}" style="margin-top: -155px; padding-top: 155px;"></div>
        {% endfor %}
      </div>
      <div class="add-inf">
        <p>
          {% translate 'Якщо ви хочете отримати більш детальну інформацію або задати питання ви можете зателефонувати або написати нам. Ми будемо раді вам допомогти!' %}
        </p>
        <div class="form-buttons">
          <a></a>
          <a class="catalog-message">
            <?xml version="1.0" encoding="UTF-8"?><svg id="_Слой_2" data-name="Слой 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42.15 30.95">
              <g id="_Слой_1-2" data-name="Слой 1">
                <path d="M42.15,4.36V26.59c-.02,.05-.05,.1-.06,.15-.59,2.73-2.42,4.21-5.21,4.21-10.59,0-21.18,0-31.77,0C2.15,30.95,0,28.81,0,25.87,0,18.94,0,12.01,0,5.08c0-.41,.03-.83,.12-1.22C.67,1.52,2.63,0,5.1,0,15.66,0,26.23,0,36.79,0c.19,0,.38,0,.58,0,1.56,.08,2.81,.73,3.78,1.96,.56,.71,.82,1.54,1,2.4ZM3.29,5.95c0,.17,0,.23,0,.3,0,6.54,0,13.09,0,19.63,0,1.09,.68,1.77,1.78,1.77,10.66,0,21.32,0,31.98,0,1.12,0,1.8-.67,1.8-1.79,0-6.52,0-13.03,0-19.55,0-.1-.02-.2-.04-.33-.2,.15-.35,.26-.51,.37-5.61,4.17-11.22,8.35-16.83,12.53-.3,.22-.48,.25-.8,.01C15.07,14.7,9.44,10.52,3.82,6.34c-.15-.11-.3-.22-.53-.39ZM36.88,3.31H5.27c5.32,3.95,10.55,7.85,15.81,11.76,5.25-3.91,10.49-7.8,15.81-11.76Z" />
              </g>
            </svg>
          </a>
          <a href="tel:+380951515315">
            <?xml version="1.0" encoding="UTF-8"?><svg id="_Слой_2" data-name="Слой 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 37.17 37.31">
              <defs></defs>
              <g id="_Слой_2-2" data-name="Слой 2">
                <path class="cls-1" d="M35.73,26.39c-.68-.67-1.36-1.35-2.04-2.03-.86-.86-1.72-1.73-2.59-2.57-1.28-1.25-2.78-1.55-4.32-.87-.65,.28-1.21,.76-1.63,1.15-.68,.63-1.33,1.3-1.97,1.95l-.36,.37c-.18-.1-.35-.2-.53-.29-.31-.17-.61-.33-.91-.52-1.72-1.1-3.32-2.45-4.9-4.14-1.26-1.35-2.67-2.99-3.65-5.04,0,0,0,0,0,0l.52-.51c.76-.74,1.54-1.51,2.26-2.31,1.45-1.61,1.44-3.75-.02-5.33-.87-.94-1.78-1.85-2.67-2.74-.52-.52-1.04-1.05-1.56-1.57-.77-.79-1.69-1.65-3.05-1.91h-1.02s-.1,0-.1,0c-.98,.2-1.83,.65-2.53,1.34-.96,.94-1.9,1.89-2.84,2.84C.66,5.39,.04,6.91,0,8.69c-.03,1.57,.25,3.19,.85,4.96,1.79,5.2,4.93,9.95,9.59,14.51,2.75,2.69,5.96,4.96,9.55,6.75,2.91,1.45,5.25,2.18,7.6,2.37,.27,.02,.53,.03,.79,.03,1.7,0,3.07-.48,4.16-1.47,1.24-1.12,2.39-2.33,3.45-3.47,1.66-1.79,1.55-4.19-.27-5.97ZM13.22,10.01c-.84,.86-1.7,1.69-2.57,2.53-.91,.87-1.05,1.63-.53,2.78,1.12,2.48,2.84,4.51,4.21,5.99,1.95,2.1,3.93,3.74,6.07,5.02,.51,.3,1.03,.57,1.56,.84,.92,.47,1.77,.33,2.52-.41,.48-.47,.95-.95,1.43-1.42l1.21-1.21c.14-.14,.28-.28,.44-.4,.38-.28,.95-.49,1.52,.06,1.89,1.86,3.43,3.39,4.83,4.83,.58,.6,.59,1.19,.02,1.81-1.01,1.1-2.04,2.16-3.07,3.15-.64,.62-1.49,.92-2.57,.89-1.71-.06-3.48-.51-5.41-1.36-7.37-3.26-13.22-8.65-17.39-16-1.23-2.16-2.03-4.24-2.46-6.37-.22-1.09-.36-2.25,.09-3.34,.19-.45,.48-.9,.84-1.29,.84-.91,1.74-1.79,2.62-2.64l.11-.11c.68-.66,1.14-.58,1.49-.42,.2,.09,.42,.26,.65,.49,1.1,1.09,2.2,2.18,3.29,3.28l1.11,1.12c.79,.84,.79,1.35,0,2.17Z" />
              </g>
            </svg>
          </a>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

{% block js %}
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  <script>
    AOS.init()
  </script>
{% endblock %}