cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path("cart-add/", views.CardAddView.as_view(), name="cart_add"),
    path("cart-change/", views.CartChangeView.as_view(), name="cart_change"),
    path("cart-remove/", views.CartRemoveView.as_view(), name="cart_remove"),
    path("carts-remove/", views.UserCartsRemoveView.as_view(), name="carts_remove"),
]

catalog/urls.py
from django.urls import path

from catalog import views

app_name = "catalog"

urlpatterns = [
    path("", views.CatalogView.as_view(), name="catalog"),
    path("", views.CatalogView.as_view(), name="search"),
    path("<slug:item_slug>", views.ItemView.as_view(), name="item"),
]

hanbild/urls.py
from django.conf.urls import handler500
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from hanbild import settings
from hanbild.settings import DEBUG

handler404 = "main.views.page404exception"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("product/", include("product.urls", namespace="product")),
    path("services/", include("solution.urls", namespace="solution")),
    path("order/", include("order.urls", namespace="order")),
    path("vacancies/", include("vacancy.urls", namespace="vacancy")),
    prefix_default_language=False,
)

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from order import views

app_name = "order"

urlpatterns = [
    path("", views.OrderView.as_view(), name="order"),
    path("success-order/", views.SuccessOrderView.as_view(), name="success-order"),
]

order/models.py
from django.db import models

from catalog.models import Goods


class OrderDetails(models.Model):
    name = models.CharField(max_length=50, verbose_name="Ім'я")
    surname = models.CharField(max_length=50, verbose_name="Прізвище")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефону")
    email = models.CharField(max_length=70, verbose_name="Email")
    city = models.CharField(max_length=30, verbose_name="Місто")
    delivery_address = models.CharField(max_length=100, verbose_name="Адреса доставки")
    message = models.TextField(verbose_name="Повідомлення", null=True, blank=True)
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата створення замовлення"
    )
    status = models.CharField(
        max_length=50, default="В обробці", verbose_name="Статус замовлення"
    )

    class Meta:
        db_table = "order"
        verbose_name = "замовлення"
        verbose_name_plural = "Замовлення"

    def __str__(self):
        return f"Замовлення № {self.pk} | Покупець {self.name} {self.surname}"


class OrderItem(models.Model):
    order = models.ForeignKey(
        to=OrderDetails, on_delete=models.CASCADE, verbose_name="Замовлення"
    )
    product = models.ForeignKey(
        to=Goods,
        on_delete=models.SET_DEFAULT,
        null=True,
        verbose_name="Товар",
        default=None,
    )
    name = models.CharField(max_length=150, verbose_name="Назва")
    price = models.FloatField(verbose_name="Ціна")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Кількість")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата продажі"
    )

    class Meta:
        db_table = "order_item"
        verbose_name = "Проданий товар"
        verbose_name_plural = "Продані товари"

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Замовлення № {self.order.pk} | Товар: {self.name}"

order/forms.py
from django import forms
from django.core.validators import EmailValidator, RegexValidator
from django.utils.translation import gettext_lazy as _

class CreateOrderForm(forms.Form):

    ukr_eng_alpha_validator = RegexValidator(
        regex=r"^[a-zA-Zа-яА-ЯіІїЇєЄґҐ.,\s`\'’-]+$",
        message=_("Поле не може містити цифри та заборонені знаки!"),
        code="invalid_characters",
    )

    name = forms.CharField(validators=[ukr_eng_alpha_validator])
    surname = forms.CharField(validators=[ukr_eng_alpha_validator])
    phone_number = forms.CharField(
        validators=[
            RegexValidator(
                regex="^\+?1?\d{9,15}$",
                message=_("Номер телефону повинен бути в форматі +380960001122 або 0960001122"),
                code="invalid_phone_number",
            )
        ]
    )
    email = forms.CharField(
        validators=[
            EmailValidator(
                message=_("Введіть коректну електронну пошту"), code="invalid_email"
            )
        ]
    )
    city = forms.CharField(validators=[ukr_eng_alpha_validator])
    delivery_address = forms.CharField(
        validators=[
            RegexValidator(
                regex=r"^[a-zA-Z0-9а-яА-ЯіІїЇєЄґҐ.,\s`'’\-/\\]+$",
                message=_("Адреса не може містити заборонені знаки!"),
                code="invalid_address_characters",
            )
        ]
    )
    message = forms.CharField(widget=forms.Textarea, required=False)

order/views.py
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from main.forms import OnlineApplicationForm
from main.utils import contact_form_errors, create_user_message
from main.views import BaseApplicationFormView
from order.forms import CreateOrderForm
from order.utils import create_order_transaction, order_fields_errors


class OrderView(TemplateView):
    """
    View class for displaying order information and interact with it
    """

    template_name = "order/order.html"
    title = _("Оформлення замовлення | HanBild.com.ua")
    # Two forms for correct applying post request
    contact_form = OnlineApplicationForm
    order_form = CreateOrderForm
    success_url = reverse_lazy("order:success-order")

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["title"] = self.title
        return context

    def form_validation(self, create_function, error_function, form, **kwargs):
        if form.is_valid():
            return create_function(form, **kwargs)
        return error_function(form, **kwargs)

    def post(self, request):
        """
        Check which form was activated
        """
        if request.POST["form-class"] == "order-form":
            return self.form_validation(
                create_order_transaction,
                order_fields_errors,
                self.order_form(request.POST),
                session_key=request.session.session_key,
                success_url=self.success_url,
            )
        elif request.POST["form-class"] == "feedback-form":
            return self.form_validation(
                create_user_message,
                contact_form_errors,
                self.contact_form(request.POST),
            )


class SuccessOrderView(BaseApplicationFormView):
    """
    View class for displaying successful order message
    """

    template_name = "order/success_order.html"
    success_url = reverse_lazy("order:success-order")
    title = _("Замовлення пройшло успішно!")

order/templates/order/order.html
{% extends 'base.html' %}
{% load carts_tags %}
{% load static %}
{% load i18n %}

{% block title %}
  {{ title }}
{% endblock %}

{% block meta %}
<meta name="robots" content="noindex, nofollow">
{% endblock %}


{% block content %}
  <main class="main">
    {% anonymous_user_carts request as carts %}

    {% if carts %}
      <div class="order">
        <div class="cart-heading">
          <h2>{% translate 'Оформлення замовлення' %}</h2>
        </div>
        <div class="order-box">
          <form action="{% url 'order:order' %}" class="order-form" method="post" id="id-order-form">
            {% csrf_token %}
            <input type="text" value="order-form" name="form-class" hidden required />
            <div class="info-container">
              <h3>{% translate 'Особисті дані' %}</h3>
              <div class="point-wrapper">
                <div class="point-container">
                  <div class="point">
                    <label for="id_name">{% translate 'Ім`я:' %}</label>
                    <input type="text" name="name" id="id_name" required placeholder="{% translate 'Микола' %}" />
                    <div class="error-massage" id="user_name_">
                      <p>
                        {% translate 'Поле не може містити цифри і заборонені знаки!' %}
                      </p>
                    </div>
                  </div>
                  <div class="point">
                    <label for="id_surname">{% translate 'Прізвище:' %}</label>
                    <input type="text" name="surname" id="id_surname" required placeholder="{% translate 'Коцюбинський' %}" />
                    <div class="error-massage" id="user_surname">
                      <p>
                        {% translate 'Поле не може містити цифри і заборонені знаки!' %}
                      </p>
                    </div>
                  </div>
                </div>
                <div class="point-container">
                  <div class="point">
                    <label for="id_phone_number">{% translate 'Номер телефону:' %}</label>
                    <input type="tel" name="phone_number" id="id_phone_number" required placeholder="+38 068 000 0000" />
                    <div class="error-massage" id="user_phone_number">
                      <p>
                        {% translate 'Поле не може містити цифри і заборонені знаки!' %}
                      </p>
                    </div>
                  </div>
                  <div class="point">
                    <label for="id_email">{% translate 'Електронна пошта:' %}</label>
                    <input type="email" name="email" id="id_email" required placeholder="handbild@gmail.com" />
                    <div class="error-massage" id="user_email">
                      <p>
                        {% translate 'Поле не може містити цифри і заборонені знаки!' %}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="info-container">
              <h3>{% translate 'Дані для доставки' %}</h3>
              <div class="point-wrapper">
                <div class="point-container">
                  <div class="point">
                    <label for="id_city">{% translate 'Місто:' %}</label>
                    <div class="autocomplete">
                      <input type="text" name="city" id="id_city" required placeholder="{% translate 'Дніпро' %}" autocomplete="off" />
                      <a id="cityDropdownButton">&#9660;</a>
                      <div id="cityDropdown" class="dropdown-content"></div>
                    </div>
                    <div class="error-massage" id="user_city">
                      <p>
                        {% translate 'Поле не може містити цифри і заборонені знаки!' %}
                      </p>
                    </div>
                  </div>
                  <div class="point">
                    <label for="id_delivery_address">{% translate 'Адреса:' %}</label>
                    <input type="text" name="delivery_address" id="id_delivery_address" required placeholder="{% translate 'вул. Дніпрянська 7' %}" />
                    <div class="error-massage" id="user_address">
                      <p>
                        {% translate 'Поле не може містити цифри і заборонені знаки!' %}
                      </p>
                    </div>
                  </div>
                </div>
                <div class="additional-order-info">
                  <?xml version="1.0" encoding="UTF-8"?><svg id="_Слой_2" data-name="Слой 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 509.34 370.13">
                    <g id="_Слой_2-2" data-name="Слой 2">
                      <path d="M498.67,277.33v-75.73c0-9.6-2.14-18.14-6.4-26.67l-27.74-50.13c-14.93-26.67-41.6-42.67-71.46-42.67h-59.21V21.33c0-11.73-9.6-21.33-21.33-21.33H21.33C9.6,0,0,9.6,0,21.33V221.87c0,10.83,8.19,19.83,18.67,21.15v34.32h0c-6.4,0-10.67,4.27-10.67,10.67v13.87c0,5.33,4.27,10.67,10.67,10.67H51.73c0,31.81,25.79,57.6,57.6,57.6s57.6-25.79,57.6-57.6h179.2c0,31.81,25.79,57.6,57.6,57.6s57.6-25.79,57.6-57.6h37.34c6.4,0,10.67-5.33,10.67-10.67v-13.87c0-6.4-4.27-10.67-10.66-10.67Zm-389.34,59.73c-13.55,0-24.53-10.98-24.53-24.53s10.98-24.53,24.53-24.53,24.54,10.98,24.54,24.53-10.99,24.53-24.54,24.53ZM357.87,109.86h34.13c20.27,0,38.4,10.67,48,27.74l26.67,49.06h-108.8V109.86Zm45.86,227.2c-13.55,0-24.53-10.98-24.53-24.53s10.98-24.53,24.53-24.53,24.54,10.98,24.54,24.53-10.99,24.53-24.54,24.53Z" />
                    </g>
                  </svg>
                  <p>
                    {% translate 'Доставка узгоджується з менеджером' %}
                  </p>
                </div>
              </div>
            </div>
            <div class="info-container">
              <h3>{% translate 'Коментар' %}</h3>
              <div class="point-wrapper">
                <div class="point">
                  <textarea name="message" id="id_message" placeholder="{% translate 'Побажання, прохання, тощо ...' %}"></textarea>
                </div>
              </div>
            </div>
          </form>

          <div class="cart-table">
            <div class="info-container">
              <h3>{% translate 'Замовлення' %}</h3>
              <div id="cartContainer">
                {% include 'cart/includes/_included_cart.html' %}
              </div>
              <div class="form-buttons">
                <a id="id-confirm-order-button" class="confirm-order-button">{% translate 'Підтвердити замовлення' %}</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% else %}
      {% include 'cart/includes/_included_empty_cart.html' %}
    {% endif %}
  </main>
{% endblock %}

{% block js %}
  <script src="{% static 'hanbild/js/cities.js' %}"></script>
  <script src="{% static 'hanbild/js/city_selector.js' %}"></script>
{% endblock %}

order/templates/order/success_order.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
{{ title }}
{% endblock title %}

{% block meta %}
<meta name="robots" content="noindex, nofollow">
{% endblock %}

{% block content %}
  <main class="main">
    <div class="empty-cart">
      <h4><span>{% translate 'Замовлення' %}</span> {% translate ' оформлене!' %}</h4>
      <img id="order-placed" src="{% static 'hanbild/icons/order-placed.svg' %}" alt="" />
      <p>
        {% translate 'Дякуємо за покупку! Ваше замовлення успішно оформлене і прийняте до обробки. Найближчим часом з вами зв`яжеться менеджер. Бажаємо гарного дня!' %}
        <a href="{% url 'catalog:catalog' %}" class="special-link">{% translate 'Переглянути інші товари.' %}</a>
      </p>
    </div>
  </main>
{% endblock %}