cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart"),
    path("cart-add/", views.CardAddView.as_view(), name="cart_add"),
    path("cart-change/", views.CartChangeView.as_view(), name="cart_change"),
    path("cart-remove/", views.CartRemoveView.as_view(), name="cart_remove"),
    path("carts-remove/", views.UserCartsRemoveView.as_view(), name="carts_remove"),
]

catalog/urls.py
from django.urls import path

from catalog import views

app_name = "catalog"

urlpatterns = [
    path("", views.CatalogView.as_view(), name="catalog"),
    path("", views.CatalogView.as_view(), name="search"),
    path("<slug:item_slug>", views.ItemView.as_view(), name="item"),
]

hanbild/urls.py
from django.conf.urls import handler500
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from hanbild import settings
from hanbild.settings import DEBUG

handler404 = "main.views.page404exception"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("product/", include("product.urls", namespace="product")),
    path("services/", include("solution.urls", namespace="solution")),
    path("order/", include("order.urls", namespace="order")),
    path("vacancies/", include("vacancy.urls", namespace="vacancy")),
    prefix_default_language=False,
)

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse

from embed_video.fields import EmbedVideoField

from catalog.utils import validate_slug
from hanbild.utils import set_translation_attrs


class Categories(models.Model):
    name = models.CharField(
        max_length=150,
        unique=True,
        verbose_name="Назва",
    )
    index_on_page = models.IntegerField(
        verbose_name="Порядковий номер",
        validators=[MinValueValidator(0)],
        default=0,
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        null=True,
        verbose_name="URL",
    )

    class Meta:
        db_table = "category"
        verbose_name = "категорію"
        verbose_name_plural = "Категорії"

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        set_translation_attrs(self, ("name",))
        return super().save(*args, **kwargs)


class Goods(models.Model):
    category = models.ForeignKey(
        to=Categories,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Категорія",
    )
    slug = models.SlugField(
        max_length=200,
        blank=True,
        null=True,
        verbose_name="URL",
    )
    name = models.CharField(
        max_length=150,
        verbose_name="Назва товару",
    )
    preview_image = models.ImageField(
        upload_to="goods_images",
        null=True,
        blank=True,
        verbose_name="Зображення",
    )
    preview_alt = models.CharField(
        verbose_name="Alt зображення",
        max_length=255,
        default="",
        blank=True,
        null=True,
    )
    price = models.FloatField(
        verbose_name="Ціна товару",
        default=0,
    )
    upload_time = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата завантаження",
    )
    description = models.TextField(
        verbose_name="Опис товару",
        null=True,
        blank=True,
    )

    meta_title = models.CharField(
        max_length=255,
        verbose_name="Назва сторінки товару",
        blank=True,
        null=True,
    )
    meta_description = models.TextField(
        verbose_name="Опис для метатегу",
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"Товар: {self.name} | Категорія: {self.category}"

    class Meta:
        db_table = "goods"
        verbose_name = "товар"
        verbose_name_plural = "Товар"

    def save(self, *args, **kwargs):
        set_translation_attrs(self, ("name", "description"))
        validate_slug(self)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("catalog:item", kwargs={"item_slug": self.slug})


class GoodsImage(models.Model):
    good = models.ForeignKey(to=Goods, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(
        upload_to="goods_images",
        verbose_name="Зображення",
        null=True,
    )
    alt = models.CharField(
        verbose_name="Alt зображення",
        max_length=255,
        blank=True,
        null=True,
        default="",
    )

    def __str__(self):
        return f"{self.good.name} - {self.image.name}"

    class Meta:
        db_table = "goods_images"
        verbose_name = "фотографію товару"
        verbose_name_plural = "Фотографії товару"


class GoodsVideo(models.Model):
    good = models.ForeignKey(to=Goods, on_delete=models.SET_NULL, null=True)
    video = EmbedVideoField(verbose_name="Посилання на відео")

    def __str__(self):
        return f"{self.good.name} - {self.video}"

    class Meta:
        db_table = "goods_videos"
        verbose_name = "відео товару"
        verbose_name_plural = "Відео товару"


class GoodsCharacteristic(models.Model):
    good = models.ForeignKey(to=Goods, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100, verbose_name="Назва характеристики")
    description = models.CharField(max_length=255, verbose_name="Опис")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "goods_characteristics"
        verbose_name = "характеристика товару"
        verbose_name_plural = "Характеристики товару"

    def save(self, *args, **kwargs):
        set_translation_attrs(self, ("name", "description"))
        return super().save(*args, **kwargs)

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from catalog.models import (
    Goods,
    GoodsCharacteristic,
    GoodsImage,
    GoodsVideo,
)
from catalog.utils import check_filters
from main.views import BaseApplicationFormView


class CatalogView(BaseApplicationFormView):
    """
    Catalog page view
    """

    template_name = "catalog/catalog.html"
    success_url = reverse_lazy("catalog:catalog")
    title = _("Каталог продукції: причепи, кузови та самоскиди від HanBild")

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # Get all goods using filters
        context["goods"] = check_filters(self.request)
        return context


class ItemView(BaseApplicationFormView):
    """
    Catalog item page view
    """

    template_name = "catalog/item.html"
    success_url = reverse_lazy("catalog:item")

    def get(self, request, item_slug, *args, **kwargs):
        # Get all item content
        item = get_object_or_404(Goods, slug=item_slug)
        item_photos = GoodsImage.objects.filter(good=item)
        item_videos = GoodsVideo.objects.filter(good=item)
        item_characteristics = GoodsCharacteristic.objects.filter(good=item)
        return render(
            request,
            self.template_name,
            {
                "item": item,
                "item_photos": item_photos,
                "item_videos": item_videos,
                "item_characteristics": item_characteristics,
            },
        )

    def dispatch(self, request, *args, **kwargs):
        """
        Function needs for reverse to the same page after appluing form
        """
        self.success_url = reverse_lazy(
            "catalog:item", kwargs={"item_slug": kwargs["item_slug"]}
        )
        return super().dispatch(request, *args, **kwargs)

catalog/templates/catalog/item.html
{% extends 'base.html' %}
{% load static %}
{% load embed_video_tags %}
{% load i18n %}

{% block title %}
  {{ item.meta_title }}
{% endblock %}

{% block meta %}
<meta name="description" content="{{ item.meta_description }}">
<meta property="og:title" content="{{ item.meta_title }}" />
<meta property="og:description" content="{{ item.meta_description }}" />
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
{% endblock %}

{% block content %}
  <main class="main">
    <div class="up-main-section">
      {% url 'catalog:catalog' as previus_url %}
      {% translate 'Каталог' as previus_title %}
      {% include 'includes/_breadcrumbs.html' with current_url=item.slug current_title=item.name|truncatechars:10 previus_url=previus_url previus_title=previus_title %}
    </div>
    <div class="single-card catalog-single-card" itemscope itemtype="https://schema.org/Product">
      <div class="single-card-left catalog-item-card">
        <div class="slider catalog-slider">
          <div class="slider-deco">
            <div class="image-slider swiper-container">
              <div class="image-slider__wrapper swiper-wrapper">
                <div class="image-slider__slide swiper-slide">
                  <div class="image-slider__image">
                    <img src="{{ item.preview_image.url }}" alt="{{ item.preview_alt }}" itemprop="image"/>
                  </div>
                </div>
                {% for photo in item_photos %}
                  <div class="image-slider__slide swiper-slide">
                    <div class="image-slider__image">
                      <img src="{{ photo.image.url }}" alt="{{ photo.alt }}" />
                    </div>
                  </div>
                {% endfor %}
                {% for item_video in item_videos %}
                  {% video item_video.video as vid %}
                  <div class="image-slider__slide swiper-slide">
                    <div class="image-slider__image">
                      <iframe id="video-slide" src="{{ vid.url }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                    </div>
                  </div>
                  {% endvideo %}
                {% endfor %}
              </div>
              <div class="button-next">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15.85 9.25">
                  <g>
                    <path d="M15.79,.93c-.13-.41-.44-.73-.83-.86h0c-.52-.16-1.01-.03-1.42,.38l-1.91,1.91c-1.23,1.23-2.46,2.46-3.69,3.69L2.37,.49c-.07-.07-.14-.13-.23-.21-.47-.38-1.15-.38-1.63,0C.19,.53,.07,.87,0,1.11v.03s0,.38,0,.38c.09,.42,.34,.7,.58,.94l2.04,2.04c1.43,1.43,2.85,2.85,4.28,4.28,.1,.1,.21,.21,.35,.28,.21,.13,.44,.19,.67,.19,.35,0,.71-.15,1-.45L15.41,2.32c.06-.07,.12-.13,.18-.2,.25-.33,.33-.77,.2-1.18Z" />
                  </g>
                </svg>
              </div>
              <div class="button-prev">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15.85 9.25">
                  <g>
                    <path d="M15.79,.93c-.13-.41-.44-.73-.83-.86h0c-.52-.16-1.01-.03-1.42,.38l-1.91,1.91c-1.23,1.23-2.46,2.46-3.69,3.69L2.37,.49c-.07-.07-.14-.13-.23-.21-.47-.38-1.15-.38-1.63,0C.19,.53,.07,.87,0,1.11v.03s0,.38,0,.38c.09,.42,.34,.7,.58,.94l2.04,2.04c1.43,1.43,2.85,2.85,4.28,4.28,.1,.1,.21,.21,.35,.28,.21,.13,.44,.19,.67,.19,.35,0,.71-.15,1-.45L15.41,2.32c.06-.07,.12-.13,.18-.2,.25-.33,.33-.77,.2-1.18Z" />
                  </g>
                </svg>
              </div>
            </div>
          </div>
          <div class="slider-deco">
            <div class="image-mini-slider swiper-container">
              <div class="image-mini-slider__wrapper swiper-wrapper">
                <div class="image-mini-slider__slide swiper-slide">
                  <div class="image-mini-slider__image">
                    <img src="{{ item.preview_image.url }}" alt="{{ item.preview_alt }}" />
                  </div>
                </div>
                {% for photo in item_photos %}
                  <div class="image-mini-slider__slide swiper-slide">
                    <div class="image-mini-slider__image">
                      <img src="{{ photo.image.url }}" alt="{{ photo.alt }}" />
                    </div>
                  </div>
                {% endfor %}
                {% for video in item_videos %}
                  <div class="image-mini-slider__slide swiper-slide">
                    <div class="image-mini-slider__image">
                      <img src="{% static 'hanbild/icons/play.svg' %}" alt="" />
                    </div>
                  </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
        <div class="close-btn">
          <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" viewBox="0 0 348.333 348.334" style="enable-background:new 0 0 512 512" xml:space="preserve" class="">
            <g>
              <path d="M336.559 68.611 231.016 174.165l105.543 105.549c15.699 15.705 15.699 41.145 0 56.85-7.844 7.844-18.128 11.769-28.407 11.769-10.296 0-20.581-3.919-28.419-11.769L174.167 231.003 68.609 336.563c-7.843 7.844-18.128 11.769-28.416 11.769-10.285 0-20.563-3.919-28.413-11.769-15.699-15.698-15.699-41.139 0-56.85l105.54-105.549L11.774 68.611c-15.699-15.699-15.699-41.145 0-56.844 15.696-15.687 41.127-15.687 56.829 0l105.563 105.554L279.721 11.767c15.705-15.687 41.139-15.687 56.832 0 15.705 15.699 15.705 41.145.006 56.844z" fill="#ffffff" opacity="1" data-original="#000000" class=""></path>
            </g>
          </svg>
        </div>
      </div>
      <div class="single-card-part hdr" id="sc1">
        <h1 itemprop="name">{{ item.name }}</h1>
        <p class="price" itemprop="offers" itemscope itemtype="https://schema.org/Offer">
          {% if item.price %}
            <span itemprop="price">{{ item.price }}</span> $
            <meta itemprop="priceCurrency" content="USD" />
          {% else %}
            {% translate 'Ціна договірна' %}
          {% endif %}
        </p>
        <p class="art">
          {% translate 'арт.' %} {{ item.pk|stringformat:'05d' }}
        </p>

        <div class="form-buttons">
          <a href="{% url 'cart:cart_add' %}" class="add-to-cart" data-product-id="{{ item.id }}">{% translate 'Додати у кошик' %}</a>
          <a class="catalog-message">
            <?xml version="1.0" encoding="UTF-8"?><svg id="_Слой_2" data-name="Слой 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42.15 30.95">
              <g id="_Слой_1-2" data-name="Слой 1">
                <path d="M42.15,4.36V26.59c-.02,.05-.05,.1-.06,.15-.59,2.73-2.42,4.21-5.21,4.21-10.59,0-21.18,0-31.77,0C2.15,30.95,0,28.81,0,25.87,0,18.94,0,12.01,0,5.08c0-.41,.03-.83,.12-1.22C.67,1.52,2.63,0,5.1,0,15.66,0,26.23,0,36.79,0c.19,0,.38,0,.58,0,1.56,.08,2.81,.73,3.78,1.96,.56,.71,.82,1.54,1,2.4ZM3.29,5.95c0,.17,0,.23,0,.3,0,6.54,0,13.09,0,19.63,0,1.09,.68,1.77,1.78,1.77,10.66,0,21.32,0,31.98,0,1.12,0,1.8-.67,1.8-1.79,0-6.52,0-13.03,0-19.55,0-.1-.02-.2-.04-.33-.2,.15-.35,.26-.51,.37-5.61,4.17-11.22,8.35-16.83,12.53-.3,.22-.48,.25-.8,.01C15.07,14.7,9.44,10.52,3.82,6.34c-.15-.11-.3-.22-.53-.39ZM36.88,3.31H5.27c5.32,3.95,10.55,7.85,15.81,11.76,5.25-3.91,10.49-7.8,15.81-11.76Z" />
              </g>
            </svg>
          </a>
        </div>
      </div>
      {% if item.description %}
      <h3 class="desc-title">{% translate 'Опис' %}</h3>
      <div class="single-card-part desc" itemprop="description">{{ item.description|linebreaks }}</div>
      {% endif %}
      <h3 class="char-title">{% translate 'Характеристики' %}</h3>
      <div class="single-card-part chars single-card-right">
        <table class="s-p-t-g s-p-t">
          <tbody>
            <tr>
              <td>
                {% translate 'Назва' %}
              </td>
              <td>{{ item.name }}</td>
            </tr>
            <tr>
              <td>
                {% translate 'Ціна' %}
              </td>
              <td>
                {% if item.price %}
                  {{ item.price }} $
                {% else %}
                  {% translate 'Ціна договірна' %}
                {% endif %}
              </td>
            </tr>
            <tr>
              <td>
                {% translate 'Артикул' %}
              </td>
              <td>{{ item.pk|stringformat:'05d' }}</td>
            </tr>
            <tr>
              <td>
                {% translate 'Категорія' %}
              </td>
              <td>
                <a style="text-decoration: underline; color: #f0500a;" href="{% url 'catalog:catalog' %}?{{ item.category.slug }}=on">{{ item.category.name }}</a>
              </td>
            </tr>
            {% for item_characteristic in item_characteristics %}
              <tr>
                <td>{{ item_characteristic.name }}</td>
                <td>{{ item_characteristic.description }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </main>
{% endblock %}

{% block js %}
  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  <script src="{% static 'hanbild/js/swiper.js' %}"></script>
{% endblock %}